<a href="https://colab.research.google.com/github/afaist/GoogleColab/blob/master/Basic_work_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [3]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones([3,4,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [0]:
x = torch.Tensor([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [6]:
x.size()

torch.Size([3, 4])

In [7]:
x.shape

torch.Size([3, 4])

In [8]:
x[0]

tensor([1., 2., 3., 4.])

In [9]:
x[1]

tensor([5., 6., 7., 8.])

In [10]:
x[0,0]

tensor(1.)

In [11]:
x[:,0]

tensor([1., 5., 9.])

In [12]:
x+10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [13]:
x**2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [0]:
y = torch.Tensor([[12,11,10,9],
                 [8,7,6,5],
                 [4,3,2,1]])

In [15]:
x+y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [16]:
x*y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [17]:
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [18]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [0]:
a = torch.ones([5,4])

In [0]:
b = torch.Tensor([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16],
                 [17,18,19,20]])

In [21]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
a%b

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
b[0]+a[2]

tensor([2., 3., 4., 5.])

В torche есть все арифметические функции

In [24]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [25]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [26]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [27]:
x > 3

tensor([[0, 0, 0, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [0]:
mask = x > 3

In [29]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [30]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [0]:
X = torch.Tensor([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [32]:
limit = int(input())

1


In [0]:
larger_than_limit_sum = (X[X > limit]).sum()

In [34]:
print(larger_than_limit_sum)

tensor(44.)


Что происходит при копировании тензора?

In [35]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [0]:
y = x

In [37]:
y[0,0] = 999
print(x)
print(y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


Видно, что x и y указывают на один и тот же тензор (копирование по ссылке). Для настоящего копирования нужно вызвать метод clone().

In [38]:
x = torch.Tensor([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
y = x.clone()
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [39]:
torch.ones(3)

tensor([1., 1., 1.])

In [40]:
x.dtype

torch.float32

In [41]:
x = x.double()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)


In [42]:
x = x.int()
print(x)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)


In [43]:
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [0]:
import numpy as np

In [0]:
x = np.array([[1,2,3,4],
             [4,3,2,1]])

In [46]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [47]:
x.numpy()

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [0]:
x = torch.rand([2,3])

Есть ли на машине GPU?

In [49]:
torch.cuda.is_available()

True

In [50]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [51]:
torch.device('cpu')

device(type='cpu')

In [52]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [53]:
x_cuda = x.to(device)
x_cuda

tensor([[0.4000, 0.3138, 0.8530],
        [0.8082, 0.8787, 0.4997]], device='cuda:0')

In [54]:
%time y = (x-x+x*10.0) ** 2

CPU times: user 178 µs, sys: 605 µs, total: 783 µs
Wall time: 683 µs


In [55]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 1.13 ms, sys: 577 µs, total: 1.71 ms
Wall time: 8.23 ms


In [0]:
x = torch.rand([2000,3000])

In [0]:
x_cuda = x.to(device)

In [58]:
%time y = (x-x+x*10.0) ** 2

CPU times: user 15 ms, sys: 37.3 ms, total: 52.3 ms
Wall time: 62.6 ms


In [59]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 2.15 ms, sys: 576 µs, total: 2.73 ms
Wall time: 2.61 ms
